name: Stealth InstaBot
on:
  push:
  workflow_dispatch: # يسمح لك بتشغيله يدوياً من GitHub

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - setup-python: '3.9'
      - run: pip install selenium requests
      - name: Start Bot
        run: python bot.py
